const $ = {
  fa: {
    url: 'https://flavourart.com/en/store/flavors/',
    container: '.ty-grid-list__item',
    flavor: '.ty-grid-list__item-name',
    link: '.add-to-cart@href',
    paginate: '.ty-pagination__next@href',
    image: '.ty-grid-list__image a img@src',
    limit: '',
  },
  cap: {
    url: 'https://www.capellaflavors.com/13ml?product_list_limit=all',
    container: '.product-item',
    flavor: '.product-item-name ',
    link: '.product-item-link@href',
    paginate: '',
    image: '.product-image-photo@src',
    limit: '',
  },
  tpa: {
    url: 'https://shop.perfumersapprentice.com/c-54-professional-flavors.aspx',
    container:
      'https://shop.perfumersapprentice.com/c-54-professional-flavors.aspx',
    flavor: '.big-links li',
    link: 'a@href',
    paginate: '',
    image: 'a@href | tpaImage',
    limit: '',
  },
  inw: {
    url: 'http://www.inaweraflavours.com/en/7-e-flavours?n=500&id_category=7',
    container: '#product_list li',
    flavor: 'h3 a',
    link: '.right_block a[title="View"]@href',
    paginate: '',
    image: '.product_img_link img@src',
    limit: '',
  },
  flv: {
    url: 'https://store.flavorah.com/view_category.asp?viewall=1&cat=97',
    container: '.product-container',
    flavor: '.name',
    link: '.name a@href',
    paginate: '',
    image: '.img a img@src',
    limit: '',
  },
  fw: {
    url:
      'https://www.flavorwest.com/water-soluble-flavoring.html?product_list_limit=all',
    container: '.product-items li',
    flavor: '.product-item-name a',
    link: '.product-item-info .product-item-photo@href',
    paginate: '',
    image: '.product-image-photo@src',
    limit: '',
  },
  fm: {
    url: 'https://www.flavormonks.com/our_flavors/',
    container: '.products li',
    flavor: 'h2',
    link: 'a@href',
    paginate: '',
    image: 'a img@src',
    limit: '',
  },
  la: {
    url: 'https://www.lorannoils.com/1-dram-size?page=10',
    container: '.ejs-productitem',
    flavor: '.box-info ul li a',
    link: '.box-info ul li a@href',
    paginate: '',
    image: '.box-photo img@src',
    limit: '',
  },
  mb: {
    url: 'https://molinberryflavours.com/category/molinberry-flavours',
    container: '#full-list .product',
    flavor: 'p.name',
    link: '.product_name@href',
    paginate: 'ul.pagination li:last-child a@href',
    image: '.image img@src',
    limit: 2,
  },
  ooo: {
    url: 'https://www.oooflavors.com/pages/flavor-list',
    container: 'div.content p span',
    flavor: 'b',
    link: 'a@href',
    paginate: '',
    image: '',
    limit: '',
  },
  vt: {
    url: 'https://www.vapetrain.com.au/product-category/vt-concentrates/',
    container: '.product-grid-item',
    flavor: 'h3.product-title',
    link: 'h3.product-title a@href',
    paginate: 'ul.page-numbers a.next@href',
    image: 'img@src',
    limit: 999,
  },
  wf: {
    url:
      'https://www.wonderflavours.com/collections/super-concentrated-flavours',
    container: 'div.grid-product',
    flavor: 'span.grid-product__title',
    link: '.grid-product__wrapper a.grid-product__meta@href',
    paginate: '',
    image: '.product--wrapper img@src',
    limit: '',
  },
}

module.exports = { $ }
